### ISSUE TITLE
dstc_register_callback_server does not re-use callbacks

### ISSUE THREAD

**Issue by smarti24** [PDXostc/dstc#42]
dstc_register_callback_server never decrements the callback_ind variable, which means that a maximum of 128 callbacks can be used before we run out of handles, causing out of memory issues.

I do not have a quick test to reproduce this issue yet, but have seen this in processes that call functions repeatedly with callbacks.

**Comment by smarti24** [comment]
Reproduction steps:

We can modify an existing example to exhibit this behavior.  Modify line 53 of ```examples/callback/callback_client.c``` so that it reads:

```
   for (int i = 0; i < 1024; ++i) {
        dstc_double_value_server(i, CLIENT_CALLBACK_ARG(double_value_callback,int,));
        dstc_process_events(10000);
    }
```
instead of just a single callback call.  You'll see, when you run the test, the following output (truncated):

```
...
Callback received: 240
Callback received: 242
Callback received: 244
Callback received: 246
Callback received: 248
Callback received: 250
Callback received: 252
Callback received: 254
[F] 1869 [UDP] dstc.c:451 epoll_ctl(modify): Bad file descriptor
```

**Comment by magnusfeuer** [comment]
examples/callback/callback_client now loops over the callback code. Using DSTC_LOG_LEVEL=6 shows that callback index 0 is reused each time instead of being incremented by one.
