### ISSUE TITLE
Chat example doesn't work with reliable_multicast

### ISSUE THREAD

**Issue by jack-sanchez** [PDXostc/dstc#5]
@magnusfeuer following the README, I tried to build and run the chat client/server example.

I cloned, init'd the submodule, then did a `make`. The results appeared successful and examples compiled and created executables. When I run these, I'm prompted for a username and upon entering some text, the programs seem to hang

**Comment by magnusfeuer** [comment]
Thanks. Known issue. Will fix.

**Comment by magnusfeuer** [comment]
Fixed in master
